import { E } from "./data.js";

export const R = ["", "I", "II", "III", "IV", "V"];
export const rom = n => R[n] || n;
export const pen = wc => Math.pow(2, wc) - 1;
export const ecost = ench => Object.entries(ench).reduce((s, [id, lvl]) => s + E[id].mult * lvl, 0);

let _uid = 0;
const nid = () => ++_uid;

export function solve(selected, itemName) {
  const ids = Object.keys(selected);
  if (!ids.length) return null;
  const n = ids.length;
  const full = (1 << n) - 1;
  const dp = new Array(1 << n).fill(null);

  for (let i = 0; i < n; i++) {
    const id = ids[i];
    dp[1 << i] = {
      nid: nid(), wc: 0, cost: 0, ench: { [id]: selected[id] },
      label: `${E[id].name} ${rom(selected[id])} Book`, steps: []
    };
  }

  for (let mask = 1; mask <= full; mask++) {
    if (!(mask & (mask - 1))) continue;
    let best = null;
    for (let sub = (mask - 1) & mask; sub > 0; sub = (sub - 1) & mask) {
      const comp = mask ^ sub;
      if (!comp || sub > comp) continue;
      const a = dp[sub], b = dp[comp];
      if (!a || !b) continue;
      for (const [tgt, sac] of [[a, b], [b, a]]) {
        const ec = ecost(sac.ench);
        const sc = pen(tgt.wc) + pen(sac.wc) + ec;
        const tc = tgt.cost + sac.cost + sc;
        const wc = Math.max(tgt.wc, sac.wc) + 1;
        if (!best || tc < best.cost) {
          const id = nid();
          best = {
            nid: id, wc, cost: tc, ench: { ...tgt.ench, ...sac.ench },
            label: Object.entries({ ...tgt.ench, ...sac.ench }).map(([i, l]) => `${E[i].name} ${rom(l)}`).join(", "),
            steps: [...tgt.steps, ...sac.steps, { tgt, sac, sc, ec, resultNid: id }]
          };
        }
      }
    }
    dp[mask] = best;
  }

  const book = dp[full];
  if (!book) return null;

  const ec = ecost(book.ench);
  const sc = pen(0) + pen(book.wc) + ec;
  const total = book.cost + sc;
  const itemNode = { nid: nid(), label: itemName };
  const allSteps = [...book.steps, { tgt: itemNode, sac: book, sc, ec, resultNid: nid(), isFinal: true }];

  const nidMap = {};
  const steps = allSteps.map((step, i) => {
    nidMap[step.resultNid] = i + 1;
    const tl = nidMap[step.tgt.nid] ? `Step ${nidMap[step.tgt.nid]} result` : step.tgt.label;
    const sl = nidMap[step.sac.nid] ? `Step ${nidMap[step.sac.nid]} result` : step.sac.label;
    return { num: i + 1, tl, sl, sc: step.sc, isFinal: !!step.isFinal };
  });

  return { steps, total, tooExpensive: steps.some(s => s.sc > 39) };
}

// Parse share URL params into { itemId, sel } or null
export function parseShareURL() {
  try {
    const params = new URLSearchParams(window.location.search);
    const item = params.get("item");
    const enc  = params.get("enc");
    if (!item || !enc) return null;
    const sel = {};
    enc.split(",").forEach(part => {
      const [id, lvl] = part.split(":");
      if (E[id]) sel[id] = parseInt(lvl) || E[id].maxLvl;
    });
    return Object.keys(sel).length ? { itemId: item, sel } : null;
  } catch { return null; }
}

// Build share URL string from current selection
export function buildShareURL(itemId, sel) {
  const enc = Object.entries(sel).map(([id, lvl]) => `${id}:${lvl}`).join(",");
  const base = window.location.origin + window.location.pathname;
  return `${base}?item=${itemId}&enc=${enc}`;
}

// Export steps to plain text
export function exportSteps(result, itemName) {
  if (!result) return "";
  const lines = [
    `⚒ ${itemName.toUpperCase()} — OPTIMAL ANVIL ORDER (${result.total} levels)`,
    "",
    ...result.steps.map(s =>
      `Step ${s.num}: [LEFT] ${s.tl}  +  [RIGHT] ${s.sl}  →  ${s.isFinal ? `✨ ${itemName}` : "combined book"}  (${s.sc} lvls)`
    ),
    "",
    result.tooExpensive ? "⚠ WARNING: A step exceeds 39 levels — may be Too Expensive in Survival." : "✓ All steps within the 39-level limit.",
    "",
    "Generated by Minecraft Enchanter Pro — minecraftenchanter.vercel.app"
  ];
  return lines.join("\n");
}
